"""add whatsapp inbound messages table

Revision ID: 59e190e569ff
Revises: 88573fd4aed2
Create Date: 2026-07-30 21:24:09.586856
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59e190e569ff'
down_revision = '88573fd4aed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_inbound_messages',
    sa.Column('wa_message_id', sa.String(length=255), nullable=False),
    sa.Column('from_phone', sa.String(length=30), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'DOCUMENT', 'UNKNOWN', name='whatsappmessagetype'), nullable=False),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'UNMATCHED', 'ACKNOWLEDGED', 'DOCUMENT_CREATED', 'ERROR', name='whatsappprocessingstatus'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_document_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_detail', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_inbound_messages_wa_message_id'), 'whatsapp_inbound_messages', ['wa_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_inbound_messages_wa_message_id'), table_name='whatsapp_inbound_messages')
    op.drop_table('whatsapp_inbound_messages')
    # ### end Alembic commands ###
