"""initial schema

Revision ID: ba50f413c7a2
Revises: 
Create Date: 2026-07-29 05:42:21.984260
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba50f413c7a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'FIRM_ADMIN', 'ACCOUNTANT', 'REVIEWER', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('assigned_accountant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_accountant_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEADLINE_REMINDER', 'MISSING_DOCUMENT', 'APPROVAL_REQUEST', 'FILING_COMPLETED', 'NEW_MESSAGE', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing_requests',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('filing_type', sa.Enum('INCOME_TAX_RETURN', 'GST_RETURN', 'TDS_RETURN', 'AUDIT', 'OTHER', name='filingtype'), nullable=False),
    sa.Column('stage', sa.Enum('REQUESTED', 'DOCUMENTS_UPLOADED', 'UNDER_REVIEW', 'APPROVAL_REQUIRED', 'FILED', 'COMPLETED', name='filingstage'), nullable=False),
    sa.Column('assigned_accountant_id', sa.UUID(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_accountant_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('filing_request_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('PAN_CARD', 'AADHAAR', 'GST_REPORT', 'SALARY_SLIP', 'INVESTMENT_PROOF', 'BANK_STATEMENT', 'INVOICE', 'OTHER', name='documentcategory'), nullable=False),
    sa.Column('status', sa.Enum('MISSING', 'UPLOADED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('replaces_document_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('reviewer_comment', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_request_id'], ['filing_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaces_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing_stage_events',
    sa.Column('filing_request_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('REQUESTED', 'DOCUMENTS_UPLOADED', 'UNDER_REVIEW', 'APPROVAL_REQUIRED', 'FILED', 'COMPLETED', name='filingstage'), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_request_id'], ['filing_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('filing_request_id', sa.UUID(), nullable=False),
    sa.Column('days_before_deadline', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', name='reminderchannel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_request_id'], ['filing_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'WAITING_FOR_DOCUMENTS', 'REVIEW', 'APPROVAL', 'FILED', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('filing_request_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_request_id'], ['filing_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('attachment_document_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('tasks')
    op.drop_table('reminders')
    op.drop_table('filing_stage_events')
    op.drop_table('documents')
    op.drop_table('filing_requests')
    op.drop_table('notifications')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('firms')
    # ### end Alembic commands ###
