"""add checklist_items table

Revision ID: e8623919c959
Revises: ba50f413c7a2
Create Date: 2026-07-29 06:53:04.185910
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8623919c959'
down_revision = 'ba50f413c7a2'
branch_labels = None
depends_on = None

# documentcategory/documentstatus were already created as PG enum types by the
# initial migration (for the documents table) — reuse them here rather than
# letting autogenerate try to CREATE TYPE a second time.
_document_category = postgresql.ENUM(
    'PAN_CARD', 'AADHAAR', 'GST_REPORT', 'SALARY_SLIP', 'INVESTMENT_PROOF',
    'BANK_STATEMENT', 'INVOICE', 'OTHER',
    name='documentcategory', create_type=False,
)
_document_status = postgresql.ENUM(
    'MISSING', 'UPLOADED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED',
    name='documentstatus', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('filing_request_id', sa.UUID(), nullable=False),
    sa.Column('category', _document_category, nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', _document_status, nullable=False),
    sa.Column('fulfilling_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_request_id'], ['filing_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fulfilling_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_request_id', 'category', name='uq_checklist_item_filing_category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_items')
    # ### end Alembic commands ###
